### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by Kalugin-Roman** [MajortomVR/simple-timer-extension#1]
Convenient and simple extension. Thank you! Is it possible to make the dropdown menu more compact? For example, two stop and start buttons to integrate into one? It would be more aesthetic. A useful feature is to repeat the last timer. Let's say by pressing the middle mouse button or the left. It is convenient if the sign ":" would be fixed in the menu. I'm just describing my operating experience :)

**Comment by MajortomVR** [comment]
Thanks for the suggestions!

> It is convenient if the sign ":" would be fixed in the menu.

Could you describe the problem and maybe how it should be?

**Comment by Kalugin-Roman** [comment]
There is no problem, I would like to improve. When opening the menu, the separator between minutes and seconds would already be in place. So that only numbers can be entered. It would be more convenient and less typing

**Comment by MajortomVR** [comment]
Thanks, i get what you mean now. That would definitely be an improvement. I'll look into it.

**Comment by Kalugin-Roman** [comment]
Thank you! The new version looks much better :)
