### ISSUE TITLE
Request: Support for Gnome 43

### ISSUE THREAD

**Issue by n3thshan** [MajortomVR/simple-timer-extension#3]
As Fedora 37 will be releasing today/tomorrow, depending on the region ofc, I would like to see this extension be supported on Gnome 43. This extension is a lifesaver, especially during timed exams as it makes me aware and also more focused. Please consider this request not only to Gnome 43 but every future release of Gnome. Thnak you!

**Comment by MajortomVR** [comment]
I've added Gnome 43 in the list of supported Versions.
I'll try to be more up-to-date with future Gnome versions pumps!
