### ISSUE TITLE
Suggestion : be able to enter "1h" or "1h15m" etc

### ISSUE THREAD

**Issue by fabd** [MajortomVR/simple-timer-extension#4]
I was desperate to find an equivalent to [Horo](https://matthewpalmer.net/horo-free-timer-mac/) which I used on my last Mac Mini -  and this works well! 

Surprising how difficult it is to find a simple app to do a timer. I was really looking for just a timer, visible in the top panel, easy to start. And this is what I was looking for :)

One thing that I liked on Horo is you could use this notation to set the time, I think this would be a neat feature:

`15m` for 15 minutes - instead of typing `15:00`

It gets more useful if you want `1h` instead of typing `1:00:00`

Now Horo had a weird limitation in that I had to type `1h 15m`with a space, oddly enough I don't know why it required the space, so that would be a potential issue to look for - being able to enter either `1h 15m` or `1h15m`.

One thing Horo did as well, though I find it less intuitive, is you can also do `90m` which is the same as `1h30m`

The way I use your app is once I click the icon I just press TAB 4 times to quickly get to the input box, then I enter eg. `30:00`then press Enter.

In that regard, wOuld it make sense also to have the input automatically focused? This could be even quicker to input - and potentially for keeping the tab order intuitive, move the controls below the input, that way if you tab one more, you get to the buttons?

Cheers

**Comment by fabd** [comment]
Awesome update! thanks! :+1:

**Comment by MajortomVR** [comment]
Glad you liked the update! Thanks for the feedback!
